Preserve layout in `optimize_single_qubit_gates`.
iqm-finland/qiskit-on-iqm pull request #119
Opened 2024-09-12 06:41 UTC by JMuff22

Fixes https://github.com/iqm-finland/qiskit-on-iqm/issues/118 

Currently, ancilla qubits are not added to the circuit. So the number of qubits in the quantum circuit is still reduced.

2024-09-12 07:40 UTC, JMuff22 commented
Additionally, the file `src/iqm/qiskit-on-iqm/iqm_transpilation.py` has additional problems:
1. Usage of single quotes. This project uses black which prefers double quotes
2. Inconsistent British and american english `optimise` vs `optimize`. Also `neighbouring`

2024-10-17 12:24 UTC, Aerylia requested changes

2024-10-17 12:24 UTC, Aerylia commented on tests/test_iqm_transpilation.py
This is a good start. Could you add some different cases? e.g. where the transpiler generates the initial layout or generates a final layout so that those are preserved as well?

2024-10-17 12:25 UTC, Aerylia commented
Thank you for taking this on!

2024-12-10 16:53 UTC, Aerylia commented
Will be obsolete with #116

2024-12-10 16:53 UTC, closed without merging