Move settings_path from IQMProvider to IQMBackend.run()
iqm-finland/qiskit-on-iqm pull request #17
Opened 2022-06-10 09:15 UTC by LeonWubben

Makes it possible to reuse Providers/Backend with different settings

2022-08-08 13:13 UTC, freetonik approved these changes

2022-08-09 12:04 UTC, q-mat-beu commented on CHANGELOG.rst
> +* Remove ``settings_path`` from ``IQMProvider`` and ``settings`` option to ``IQMBackend.run``. `#17 <https://github.com/iqm-finland/qiskit-on-iqm/pull/17>`_
```suggestion
* Remove ``settings_path`` from ``IQMProvider`` and add ``settings`` option to ``IQMBackend.run``. `#17 <https://github.com/iqm-finland/qiskit-on-iqm/pull/17>`_
```

2022-08-09 12:24 UTC, smite commented on docs/user_guide.rst
> +        print(job.result().get_counts())
Since I can't comment on unchanged lines:
See line 129 below. Is batch execution still experimental?

2022-08-09 12:28 UTC, smite requested changes

2022-08-09 12:28 UTC, smite commented on src/qiskit_iqm/iqm_backend.py
> +            ):
```suggestion
            if any(mapping != mappings[0] for mapping in mappings):
```

2022-08-09 12:30 UTC, smite commented on src/qiskit_iqm/qiskit_to_iqm.py
> +    }
```suggestion
    return {qubit_to_name(k, circuit): v for k, v in qubit_mapping.items()}
```

2022-08-09 14:08 UTC, hay-k commented on docs/user_guide.rst
> +        print(job.result().get_counts())
I think the 'experimental' there was supposed to refer to the fact that it is intended for parametrized circuits only. I can rephrase the sentence a bit to remove the word 'experimental'.

2022-08-09 14:24 UTC, smite approved these changes

2022-08-09 14:51 UTC, merged