Change documentation theme
iqm-finland/qiskit-on-iqm pull request #6
Opened 2022-03-29 15:03 UTC by LeonWubben

Theme is now sphinx_book_theme in line with other IQM documentations

Changed the logo to transparent

2022-03-29 16:00 UTC, hay-k commented on docs/conf.py
```suggestion

html_theme_options = {
    'logo_only': True,
}
```

2022-03-29 16:01 UTC, hay-k commented on docs/conf.py
```suggestion

html_theme_options = {
    'logo_only': True,
}
```

2022-03-30 12:12 UTC, hay-k approved these changes

2022-03-31 09:58 UTC, smite requested changes

2022-03-31 09:58 UTC, smite commented on setup.cfg
> +    sphinx-book-theme == 0.1.10
```suggestion
    sphinx == 4.5.0
    sphinx-book-theme == 0.3.2
```

2022-03-31 09:58 UTC, smite commented on setup.cfg
> +    sphinx-book-theme == 0.1.10
I would just use the latest versions.

2022-04-06 10:06 UTC, smite approved these changes

2022-04-06 11:31 UTC, merged